baseurl = "https://www.mytinyshinys.com/"  
languageCode = "en-us" # might want to change
title = "Interactive Apps for the Modern World"
# Enable comments by entering your Disqus shortname
#disqusShortname = "spf13" Ed Borasky recommends against - setting to "" apparantly does this
disqusShortname = "mytinyshinys"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-87354792-2"
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"


ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug"


[params]
    # Tell me who you are
    author = "Andrew Clark"
    bio = "Consultant/Contractor for shiny and htmlwidget apps"
    location = "N. Vancouver, B.C"
    site_description = ""
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."
    avatar = "css/images/pssguy.jpg"
    #logo = "css/images/myTinyShinys.png" # themes/icarus/static/css/images - need to change
    disable_mathjax = false # set to true to disable MathJax

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = ["css/custom.css"]
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Packages" #Renamed - on clicking still sgows Tags as heading
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

## added came up on main menu but no page automatically created
[[params.menu]]
    before = false
    label  = "Resources"
    link   = "info.html"  ## but put in static folder I think - did this by taking md/Rmd file previewing it as HTML then opening in browser,copying view source
#  copying to Notebook and saving as in static  info.html - then build site and upload - as single file if necessary(check it has been transferred to public)


# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://twitter.com/pssGuy" # see also data/l10n.toml


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "pssguy"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = "535458"
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "pssguy"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = false
    tags = false
    tag_cloud = false
