---
title: EPL week 15
author: Andrew Clark
date: '2017-12-05'
slug: epl-week-15
categories:
  - eplWeekly
tags: []
banner: 'banners/wk14_2017.png'
description: 
images: []
menu: ''
---

```{r, echo=FALSE}
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message=FALSE, echo=FALSE, fig.align = 'center')
```



```{r setup}



library(tidyverse) #for data carpentry
library(plotly) # for plots
library(DT) # for tables
library(vembedr) # for videos
library(blogdown) # for shortcode
library(glue)



# library(stringr)
# library(vembedr) 
# library(blogdown)
# library(lubridate)
# library(crosstalk)
# library(forcats)
# library(glue)
# library(htmltools)

#library(sparkline)


standings<- readRDS("data/soccer/standings.rds")
hth<- readRDS("data/soccer/hth.rds")

goals<- readRDS("data/soccer/goals.rds")
playerGame<- readRDS("data/soccer/playerGame.rds")
teamGames<- readRDS("data/soccer/teamGames.rds")
# assists<- readRDS("data/soccer/assists.rds")
#scoreLines<- readRDS("data/soccer/scoreLines.rds") #



```



## Match of the Day



```{r topGame}

embed_youtube("JddLLNc2tvw", width = 420, height = 315, frameborder = 0,
   allowfullscreen = TRUE, query = NULL) 


```

***



***


## Totally Football and Guardian Weekly Review Podcasts



<iframe width="100%" height="300" style="background-color:transparent; display:block; padding: 0; max-width: 700px;" frameborder="0" allowtransparency="allowtransparency" scrolling="no" src="//embeds.audioboom.com/posts/6527110-rejuvenated-rooney-sterling-and-salah-strike-again-and-presumptuous-pep-talks/embed/v4?eid=AQAAAABgIFqGmGMA" title="audioBoom player"></iframe>

<iframe width="100%" height="300" style="background-color:transparent; display:block; padding: 0; max-width: 700px;" frameborder="0" allowtransparency="allowtransparency" scrolling="no" src="//embeds.audioboom.com/posts/6527311-raheem-sterling-english-managers-and-the-world-cup-draw-football-weekly-extra/embed/v4?eid=AQAAAK9fIFpPmWMA" title="audioBoom player"></iframe>

***

## Results and Table

```{r results}
## results - amy have to copy and run in console
hth %>% 
  filter(season=="2017/18"&gameDate>="2017-11-30"&gameDate<="2017-12-04") %>% ## may need to put in day later?
  filter(venue=="H") %>% 
  arrange(team) %>% 
  select(Home=team,GF,GA,Away=OppTeam) %>% 
  DT::datatable(rownames=FALSE,class='compact stripe hover row-border',colnames = c('', '', '', ''),
                options= list(paging = FALSE, searching = FALSE,info=FALSE,
                              columnDefs = list(list(width = '40%', targets = list(0,3)))),width=250)
```



```{r standings}


# table
hth %>% 
  filter(season=="2017/18"&gameDate<="2017-12-04") %>% 
  group_by(team) %>% 
  mutate(W = ifelse(res=="Win",1,0),L = ifelse(res=="Loss",1,0),D = ifelse(res=="Draw",1,0)) %>%
  summarise(P=n(),Pts=sum(points),W=sum(W),D=sum(D),L=sum(L),GD=sum(GF)-sum(GA),GF=sum(GF)) %>% 
  arrange(desc(Pts),desc(GD),desc(GF),team) %>%
  DT::datatable(class='compact stripe hover row-border order-column',colnames = c('', 'P', 'Pts', 'W','D', 'L', 'GD','GF'),
                rownames=TRUE,options= list(paging = FALSE, searching = FALSE,info=FALSE))


```


## Final Factoid

<p class="factoid"></p>


---



Plenty more NEW data at the [premiersoccerstats site](https://mytinyshinys.shinyapps.io/premierLeague/)

Feel free to contact me if you have any questions or work offers
